plugins {
    id "com.android.library"
}

android {
    namespace "cloud.unum.usearch.android"
    compileSdk 37

    defaultConfig {
        minSdk 23

        ndk {
            abiFilters "arm64-v8a"
        }

        externalNativeBuild {
            cmake {
                arguments "-DUSEARCH_BUILD_JNI=ON",
                        "-DUSEARCH_BUILD_TEST_CPP=OFF",
                        "-DUSEARCH_BUILD_BENCH_CPP=OFF",
                        "-DUSEARCH_BUILD_LIB_C=OFF",
                        "-DUSEARCH_USE_OPENMP=OFF",
                        "-DUSEARCH_USE_JEMALLOC=OFF",
                        "-DUSEARCH_USE_NUMKONG=ON",
                        "-DNK_TARGET_NEON=ON",
                        "-DNK_TARGET_NEONBFDOT=ON",
                        "-DNK_TARGET_NEONHALF=ON",
                        "-DNK_TARGET_NEONSDOT=ON",
                        "-DNK_DYNAMIC_DISPATCH=ON",
                        "-DCMAKE_ANDROID_STL_TYPE=c++_static"
                cppFlags "-std=c++17", "-fexceptions", "-frtti"
            }
        }

        consumerProguardFiles "consumer-rules.pro"
    }

    sourceSets {
        main {
            java {
                srcDirs "src/main/java", "../../java"
                exclude "test/**"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file("../../CMakeLists.txt")
        }
    }
}
